version: 0.2

env:
  variables:
    # enables continuous integration settings for react-scripts
    CI: false

phases:
  install:
    commands:
      # runs
      - npx yarn install
  pre_build:
    commands:
      # - npm run test
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build
